name: MineNite
version: @version@
main: org.minenite.plugin.MineNite
authors: [AndrewAubury, PiggyPiglet]
website: https://minenite.org
description: Play Fortnite inside minecraft
commands:
  minenite:
    description: The main MineNite command
    aliases: [mn, fortnite, fn]